global:
  scrape_interval: 10s

# rule_files:
#   - "/etc/prometheus/rules_alerts/free_resource_percentage.yml"
#   - "/etc/prometheus/rules_alerts/free_resource.yml"

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - "localhost:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

#   - job_name: 'node_exporter'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:9100']
